apiVersion: v1
kind: ConfigMap
metadata:
  name: neuralscape-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neuralscape.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
