apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neuralscape.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.gcpServiceAccountEmail }}
  annotations:
    iam.gke.io/gcp-service-account: {{ . }}
  {{- end }}
