"""``neuralscape`` — the solo engine CLI (unit 6 of 28-solo-engine.md §6).

You install an engine only if you host one: this CLI is for solo hosts.
Team members configure a URL + token in the plugin and never run it; team
admins deploy compose/Helm exactly as before.

Commands:

- ``init``    — set up a solo daemon: env file, data dirs, service unit
                (launchd on macOS, systemd --user on Linux), start, doctor.
- ``serve``   — run the daemon in the foreground (what the service unit runs).
- ``doctor``  — health + storage self-check; ``--deep`` adds a write/recall
                round-trip through the running daemon.
- ``export``  — versioned backup bundle (tar.gz of the data home + manifest).
- ``import``  — restore a bundle into the data home (daemon must be stopped).
- ``status``  — one-line daemon status.

stdlib-only (argparse/urllib/tarfile) so the CLI adds no dependencies.
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import subprocess
import sys
import tarfile
from datetime import datetime, timezone
from pathlib import Path

BUNDLE_VERSION = 1
DEFAULT_PORT = 8199
LAUNCHD_LABEL = "dev.neuralscape.solo"

# The env template mirrors the e2e-verified solo configuration exactly:
# embedded stores under the data home, no Redis, no Neo4j server, no auth
# (single local user). Every value remains overridable by editing the file.
_ENV_TEMPLATE = """# Neuralscape solo engine — generated by `neuralscape init`
NS_MODE=solo
GOOGLE_API_KEY={api_key}
PORT={port}
REDIS_URL=
QDRANT_URL=
NEO4J_URI=
NEO4J_PASSWORD=
AUTH_PROVIDER=token
QDRANT_PATH={home}/qdrant
KUZU_PATH={home}/graph.kuzu
INGEST_STORAGE_DIR={home}/ingest
EXTRACTION_SETTINGS_PATH={home}/extraction_settings.json
EVENT_STREAM_ENABLED=true
DOCLING_ENABLED=false
"""


def _home(args) -> Path:
    return Path(getattr(args, "home", None) or "~/.neuralscape").expanduser()


def _env_path(home: Path) -> Path:
    return home / "env"


def _daemon_binary() -> list[str]:
    """The command a service unit should exec for ``serve``."""
    exe = shutil.which("neuralscape")
    if exe:
        return [exe, "serve"]
    # Editable/dev installs: fall back to this interpreter + module.
    return [sys.executable, str(Path(__file__).resolve().parent / "main.py")]


def _base_url(port: int) -> str:
    return f"http://localhost:{port}"


def _http_json(url: str, payload: dict | None = None, timeout: float = 30.0):
    import urllib.request

    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(
        url, data=data, headers={"Content-Type": "application/json"}
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:  # noqa: S310 — localhost
        return json.loads(resp.read().decode())


# ── init ─────────────────────────────────────────────────────────────


def write_env_file(home: Path, api_key: str, port: int) -> Path:
    home.mkdir(parents=True, exist_ok=True)
    for sub in ("qdrant", "ingest", "logs"):
        (home / sub).mkdir(exist_ok=True)
    path = _env_path(home)
    path.write_text(_ENV_TEMPLATE.format(api_key=api_key, port=port, home=home))
    path.chmod(0o600)  # holds the API key
    return path


def render_launchd_plist(home: Path, exec_cmd: list[str]) -> str:
    # launchd has no EnvironmentFile: source the env file in a shell wrapper.
    shell_cmd = f'set -a; . "{_env_path(home)}"; exec ' + " ".join(
        f'"{part}"' for part in exec_cmd
    )
    log = home / "logs" / "daemon.log"
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>{LAUNCHD_LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/sh</string>
        <string>-c</string>
        <string>{shell_cmd}</string>
    </array>
    <key>RunAtLoad</key><true/>
    <key>KeepAlive</key><true/>
    <key>StandardOutPath</key><string>{log}</string>
    <key>StandardErrorPath</key><string>{log}</string>
</dict>
</plist>
"""


def render_systemd_unit(home: Path, exec_cmd: list[str]) -> str:
    return f"""[Unit]
Description=Neuralscape solo engine
After=network.target

[Service]
EnvironmentFile={_env_path(home)}
ExecStart={" ".join(exec_cmd)}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
"""


def install_service(home: Path) -> str:
    """Write + activate the platform service unit; returns a description."""
    exec_cmd = _daemon_binary()
    if platform.system() == "Darwin":
        plist = Path("~/Library/LaunchAgents").expanduser() / f"{LAUNCHD_LABEL}.plist"
        plist.parent.mkdir(parents=True, exist_ok=True)
        plist.write_text(render_launchd_plist(home, exec_cmd))
        subprocess.run(["launchctl", "unload", str(plist)], capture_output=True)
        subprocess.run(["launchctl", "load", str(plist)], check=True, capture_output=True)
        return f"launchd agent {plist}"
    unit = Path("~/.config/systemd/user").expanduser() / "neuralscape.service"
    unit.parent.mkdir(parents=True, exist_ok=True)
    unit.write_text(render_systemd_unit(home, exec_cmd))
    subprocess.run(["systemctl", "--user", "daemon-reload"], check=True, capture_output=True)
    subprocess.run(
        ["systemctl", "--user", "enable", "--now", "neuralscape.service"],
        check=True,
        capture_output=True,
    )
    return f"systemd user unit {unit}"


def cmd_init(args) -> int:
    home = _home(args)
    api_key = args.api_key or os.environ.get("GOOGLE_API_KEY") or ""
    if not api_key and sys.stdin.isatty():
        api_key = input("Gemini API key (GOOGLE_API_KEY): ").strip()
    if not api_key:
        print("error: an API key is required (pass --api-key or set GOOGLE_API_KEY)")
        return 1
    env_file = write_env_file(home, api_key, args.port)
    print(f"wrote {env_file}")
    if args.no_service:
        cmd = " ".join(_daemon_binary())
        print(f"service install skipped — start manually with:\n  set -a; . {env_file}; {cmd}")
        return 0
    try:
        desc = install_service(home)
        print(f"installed + started {desc}")
    except Exception as e:  # noqa: BLE001 — surface, don't stack-trace
        print(f"error: service install failed: {e}")
        return 1
    print(
        "\nNext steps:\n"
        f"  1. neuralscape doctor            # verify the daemon on port {args.port}\n"
        "  2. Install the Claude Code plugin — it already defaults to "
        f"{_base_url(args.port)}\n"
    )
    return 0


# ── serve / status / doctor ──────────────────────────────────────────


def cmd_serve(_args) -> int:
    import uvicorn

    from config import settings

    uvicorn.run("main:app", host=settings.host, port=settings.port)
    return 0


def cmd_status(args) -> int:
    url = _base_url(args.port)
    try:
        alive = _http_json(f"{url}/health/live", timeout=3)
        print(f"daemon: {alive.get('status', 'unknown')} at {url}")
        return 0
    except Exception:
        print(f"daemon: unreachable at {url}")
        return 1


def cmd_doctor(args) -> int:
    home = _home(args)
    url = _base_url(args.port)
    failures = 0

    def check(label: str, ok: bool, detail: str = "") -> None:
        nonlocal failures
        mark = "ok " if ok else "FAIL"
        print(f"[{mark}] {label}" + (f" — {detail}" if detail else ""))
        if not ok:
            failures += 1

    env_file = _env_path(home)
    check("env file", env_file.is_file(), str(env_file))
    check(
        "api key configured",
        env_file.is_file() and "GOOGLE_API_KEY=" in env_file.read_text()
        and not any(
            line.strip() == "GOOGLE_API_KEY="
            for line in env_file.read_text().splitlines()
        ),
    )
    check("data home writable", os.access(home, os.W_OK), str(home))
    try:
        health = _http_json(f"{url}/health", timeout=15)
        checks = health.get("checks", {})
        check("daemon reachable", True, url)
        check("vector store", checks.get("vector_store") == "ok")
        check("graph store", checks.get("graph_store") == "ok")
        check("task backend", checks.get("redis") in ("inline", "ok"), checks.get("redis", ""))
    except Exception as e:  # noqa: BLE001
        check("daemon reachable", False, f"{url} ({e})")

    if args.deep and failures == 0:
        try:
            import time as _time

            probe = f"doctor probe {datetime.now(timezone.utc).isoformat()}"
            accepted = _http_json(
                f"{url}/v1/memories/raw",
                {"content": probe, "user_id": "doctor", "category": "task_context"},
                timeout=60,
            )
            # Writes are 202-and-poll (inline backend included): wait for the
            # task to land before searching, or the probe races its own write.
            task_id = accepted.get("task_id")
            deadline = _time.monotonic() + 60
            status = accepted.get("status")
            while task_id and status not in ("completed", "failed", "not_found"):
                if _time.monotonic() > deadline:
                    break
                _time.sleep(1.0)
                status = _http_json(
                    f"{url}/v1/memories/status/{task_id}", timeout=15
                ).get("status")
            found = _http_json(
                f"{url}/v1/search",
                {"query": "doctor probe", "user_id": "doctor", "limit": 3},
                timeout=60,
            )
            hits = found.get("results", [])
            check(
                "write/recall round-trip",
                any(probe in (r.get("memory") or "") for r in hits),
                f"task {status}",
            )
        except Exception as e:  # noqa: BLE001
            check("write/recall round-trip", False, str(e))

    print("all checks passed" if failures == 0 else f"{failures} check(s) failed")
    return 0 if failures == 0 else 1


# ── export / import ──────────────────────────────────────────────────

_BUNDLE_DIRS = ("qdrant", "ingest")
_BUNDLE_FILES = ("graph.kuzu", "extraction_settings.json", "savings.json")


def cmd_export(args) -> int:
    home = _home(args)
    if not home.is_dir():
        print(f"error: no data home at {home}")
        return 1
    out = Path(
        args.output
        or f"neuralscape-backup-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.tar.gz"
    ).expanduser()
    manifest = {
        "bundle_version": BUNDLE_VERSION,
        "kind": "solo-file-backup",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "home": str(home),
        "contents": [],
    }
    with tarfile.open(out, "w:gz") as tar:
        for name in (*_BUNDLE_DIRS, *_BUNDLE_FILES):
            src = home / name
            if src.exists():
                tar.add(src, arcname=name)
                manifest["contents"].append(name)
        manifest_bytes = json.dumps(manifest, indent=2).encode()
        info = tarfile.TarInfo("manifest.json")
        info.size = len(manifest_bytes)
        import io

        tar.addfile(info, io.BytesIO(manifest_bytes))
    print(f"exported {', '.join(manifest['contents']) or 'nothing'} → {out}")
    print("note: stop the daemon before exporting for a consistent snapshot")
    return 0


def _safe_members(tar: tarfile.TarFile):
    """Refuse absolute paths and parent-escapes (tar-slip guard)."""
    for member in tar.getmembers():
        name = Path(member.name)
        if name.is_absolute() or ".." in name.parts:
            raise ValueError(f"unsafe path in bundle: {member.name}")
        yield member


def cmd_import(args) -> int:
    home = _home(args)
    bundle = Path(args.bundle).expanduser()
    if not bundle.is_file():
        print(f"error: bundle not found: {bundle}")
        return 1
    with tarfile.open(bundle, "r:gz") as tar:
        names = tar.getnames()
        if "manifest.json" not in names:
            print("error: not a neuralscape bundle (no manifest.json)")
            return 1
        manifest = json.loads(tar.extractfile("manifest.json").read())
        if manifest.get("bundle_version") != BUNDLE_VERSION:
            print(f"error: unsupported bundle_version {manifest.get('bundle_version')}")
            return 1
        existing = [n for n in manifest.get("contents", []) if (home / n).exists()]
        if existing and not args.force:
            print(
                f"error: {home} already contains {', '.join(existing)} — "
                "re-run with --force to overwrite (stop the daemon first)"
            )
            return 1
        for name in existing:
            target = home / name
            if target.is_dir():
                shutil.rmtree(target)
            else:
                target.unlink()
        home.mkdir(parents=True, exist_ok=True)
        # filter="data" (PEP 706) strips setuid/devices/absolute links on top
        # of the explicit tar-slip guard in _safe_members.
        tar.extractall(home, members=_safe_members(tar), filter="data")
    (home / "manifest.json").unlink(missing_ok=True)
    print(f"imported {', '.join(manifest.get('contents', []))} → {home}")
    return 0


# ── entry point ──────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="neuralscape", description="Neuralscape solo engine CLI"
    )
    parser.add_argument("--home", help="data home (default ~/.neuralscape)")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    sub = parser.add_subparsers(dest="command", required=True)

    p_init = sub.add_parser("init", help="set up and start a solo daemon")
    p_init.add_argument("--api-key", help="Gemini API key (or set GOOGLE_API_KEY)")
    p_init.add_argument(
        "--no-service", action="store_true", help="write config only; no service unit"
    )
    sub.add_parser("serve", help="run the daemon in the foreground")
    sub.add_parser("status", help="one-line daemon status")
    p_doc = sub.add_parser("doctor", help="self-check")
    p_doc.add_argument("--deep", action="store_true", help="write/recall round-trip")
    p_exp = sub.add_parser("export", help="backup bundle (tar.gz + manifest)")
    p_exp.add_argument("--output", help="output path")
    p_imp = sub.add_parser("import", help="restore a backup bundle")
    p_imp.add_argument("bundle")
    p_imp.add_argument("--force", action="store_true", help="overwrite existing data")

    args = parser.parse_args(argv)
    handler = {
        "init": cmd_init,
        "serve": cmd_serve,
        "status": cmd_status,
        "doctor": cmd_doctor,
        "export": cmd_export,
        "import": cmd_import,
    }[args.command]
    return handler(args)


if __name__ == "__main__":
    raise SystemExit(main())
