#!/usr/bin/env node
import{appendFile as De,mkdir as Me,readdir as oe,readFile as se,stat as ie,unlink as je,writeFile as Fe}from"node:fs/promises";import{existsSync as ae,readFileSync as P}from"node:fs";import{homedir as ce}from"node:os";import{dirname as le,join as h,parse as T}from"node:path";function m(e,t=""){let n=process.env[`CLAUDE_PLUGIN_OPTION_${e}`]?.trim();if(n)return n;let r=process.env[`NEURALSCAPE_${e}`]?.trim();return r||t}function ue(){let e=process.env.CLAUDE_PLUGIN_ROOT?.trim();if(!e)return"";try{let n=JSON.parse(P(h(e,".mcp.json"),"utf8"))?.mcpServers?.neuralscape?.url;if(typeof n!="string"||n.includes("${"))return"";let r=new URL(n);if(r.protocol!=="http:"&&r.protocol!=="https:")return"";let s=r.pathname.replace(/\/mcp\/?$/,"").replace(/\/$/,"");return`${r.origin}${s}`}catch{return""}}var de=(m("URL","")||ue()||"http://localhost:8199").replace(/\/$/,""),I=m("API_KEY",""),R=m("USER_ID","")||process.env.USER?.trim()||process.env.USERNAME?.trim()||"",pe=8e3;function fe(){let e={"Content-Type":"application/json"};return I&&(e.Authorization=`Bearer ${I}`),e}var y=class extends Error{constructor(t){super(`malformed hook input (client bug): ${t}`),this.name="MalformedHookInputError"}};async function C(){let e=await new Promise(t=>{let n="";process.stdin.setEncoding("utf-8"),process.stdin.on("data",r=>{n+=r}),process.stdin.on("end",()=>t(n)),process.stdin.readableEnded&&t(n)});if(!e.trim())throw new y("empty stdin");try{return JSON.parse(e)}catch{throw new y("stdin is not valid JSON")}}function O(){return R}function D(){return R.length>0}var $=".neuralscape-project";function A(e,t){let n=e;for(;;){if(ae(h(n,t)))return n;let r=le(n);if(r===n)return;n=r}}function M(e){let t=m("PROJECT_ID","").trim();if(t)return t;let n=e||process.cwd(),r=A(n,$);if(r){try{let o=P(h(r,$),"utf8").trim().split(/\r?\n/)[0]?.trim();if(o)return o}catch{}return T(r).name||void 0}let s=A(n,".git");return s?T(s).name||void 0:T(n).name||void 0}async function x(e,t){let n=new URL(`${de}${e}`);if(t)for(let[o,i]of Object.entries(t))n.searchParams.set(o,i);let r=new AbortController,s=setTimeout(()=>r.abort(),pe);try{let o=await fetch(n.toString(),{method:"GET",headers:fe(),signal:r.signal});if(!o.ok)throw new Error(`HTTP ${o.status}: ${o.statusText}`);return await o.json()}finally{clearTimeout(s)}}function j(e){process.stdout.write(JSON.stringify(e))}function E(){j({continue:!0,suppressOutput:!0})}function S(e,t="SessionStart"){j({continue:!0,hookSpecificOutput:{hookEventName:t,additionalContext:e}})}function b(e,t){let n=t instanceof Error?t.message:String(t||"");process.stderr.write(`[neuralscape] ${e}${n?`: ${n}`:""}
`)}function ge(){let e=process.env.CLAUDE_PLUGIN_DATA?.trim();return e?h(e,"observations"):h(ce(),".neuralscape","observations")}async function me(e){let t=T(e).name,n=0,r=null;try{let i=(await se(e,"utf-8")).split(`
`).filter(c=>c.trim());if(n=i.length,i.length>0)try{let c=JSON.parse(i[0]);r=typeof c.ts=="string"?c.ts:null}catch{}}catch{}let s=!1;try{await ie(e+".stale"),s=!0}catch{s=!1}return{path:e,sessionId:t,lineCount:n,oldestTs:r,isStale:s}}async function F(e){let t=ge(),n=[];try{n=await oe(t)}catch{return[]}let r=[];for(let s of n){if(!s.endsWith(".jsonl"))continue;let o=h(t,s),i=await me(o);i.lineCount!==0&&(e&&i.sessionId===e||r.push(i))}return r}function k(e){return e?Math.max(1,Math.ceil(e.length/4)):1}var he={bugfix:"\u{1F41B}",feature:"\u2728",refactor:"\u267B",decision:"\u2696",discovery:"\u{1F50D}",gotcha:"\u26A0",pattern:"\u25C7",trade_off:"\u21C4",research_note:"\u{1F4DD}",meeting_outcome:"\u{1F91D}",task_plan:"\u{1F5FA}",fact:"\u2022",reflection:"\u{1F4AD}"},L="\xB7";function ye(e){return e?he[e]??L:L}var U=10,B=80;function be(e){if(!e||!e.trim())return"(untitled)";let s=(((e.split(`
`).map(c=>c.replace(/^[\s#>*+\-`~|:\d.)\]\[]+/,"").trim()).find(c=>c.length>0)??"").split(/(?<=[.!?])\s+/)[0]?.replace(/[.!?]+$/,"").trim()??"")||e.replace(/\s+/g," ").trim()).split(/\s+/),o=s.slice(0,U).join(" "),i=s.length>U;return o.length>B&&(o=o.slice(0,B-1).trimEnd(),i=!0),i?`${o} \u2026`:o}function G(e){return{id:e.id,title:e.title||be(e.memory),category:e.category||"memory",glyph:ye(e.observation_type),createdAt:e.created_at??null,tokens:e.token_estimate||k(e.memory)}}var _e=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];function w(e){let t=e.getFullYear(),n=String(e.getMonth()+1).padStart(2,"0"),r=String(e.getDate()).padStart(2,"0");return`${t}-${n}-${r}`}function xe(e,t=new Date){if(!e)return"Undated";let n=new Date(e);if(Number.isNaN(n.getTime()))return"Undated";let r=w(n);if(r===w(t))return"Today";let s=new Date(t.getTime()-1440*60*1e3);return r===w(s)?"Yesterday":`${_e[n.getDay()]} ${r}`}function Ee(e){if(!e)return"--:--";let t=new Date(e);if(Number.isNaN(t.getTime()))return"--:--";let n=String(t.getHours()).padStart(2,"0"),r=String(t.getMinutes()).padStart(2,"0");return`${n}:${r}`}function Te(e){return`#${e.id} | ${Ee(e.createdAt)} | ${e.glyph} ${e.category} | ${e.title} | ~${e.tokens}`}function Y(e,t={}){let n=t.budgetTokens??1500,r=t.now??new Date,s=[...e].sort((a,l)=>{let u=a.createdAt?new Date(a.createdAt).getTime():Number.NEGATIVE_INFINITY,d=l.createdAt?new Date(l.createdAt).getTime():Number.NEGATIVE_INFINITY;return(Number.isNaN(d)?Number.NEGATIVE_INFINITY:d)-(Number.isNaN(u)?Number.NEGATIVE_INFINITY:u)}),o=[],i=0,c=0,p=0,f=null;for(let a of s){let l=xe(a.createdAt,r),u=[];l!==f&&u.push(`### ${l}`),u.push(Te(a));let d=u.reduce((N,re)=>N+k(re),0);if(i+d>n&&p>0||(l!==f&&(f=l),o.push(...u),i+=d,c+=a.tokens,p++,i>=n))break}let g=s.length-p;if(g>0){let a=`\u2026 ${g} more not shown \u2014 recall_memories(query=\u2026, index_only=true) to browse the rest.`;o.push(a),i+=k(a)}return{text:o.join(`
`),included:p,total:s.length,servedTokens:i,baselineTokens:c}}function H(e){let t=e.baselineTokens>0?Math.max(0,Math.round((1-e.servedTokens/e.baselineTokens)*100)):0;return`index: ${e.included<e.total?`${e.included} of ${e.total}`:`${e.included}`} memories, ~${e.servedTokens} tokens vs ~${e.baselineTokens} full`+(e.baselineTokens>0?` (${t}% saved)`:"")}var _="mcp__plugin_neuralscape_neuralscape__";function v(e){let t=["## Using this index","","The table above is an index, not the memories themselves. Escalate only when needed:","","1. **Scan** the rows \u2014 title + glyph + recency (day heading + time) is usually enough to decide relevance.",`2. **Search** for more: \`${_}recall_memories\` with \`index_only: true\` returns the same compact rows for any query.`,`3. **Expand** the few that matter: \`${_}get_memories\` with \`ids: [...]\` (the \`#id\` values above; batch up to 50).`,`4. **History** around a moment: \`${_}timeline\` with \`anchor\` = a memory id or query.`,"","Never expand rows speculatively \u2014 fetch full payloads only for memories you will actually use."];return e&&t.push("","### Code structure \u2014 defer to the code graph (F2)","",`This project has a Graphify code graph behind Neuralscape. For questions about code *structure* (what calls what, module layout, dependency paths), use \`${_}query_code_graph\`, \`${_}get_code_neighbors\`, or \`${_}code_path\` instead of searching memories \u2014 and do NOT store purely structural observations as memories (structure rots with every commit; the graph is the source of truth). Memories are for decisions, gotchas, and rationale *about* the code.`),t.join(`
`)}var W=[["request","Request"],["investigated","Investigated"],["learned","Learned"],["completed","Completed"],["next_steps","Next steps"]];function K(e){if(!e||!e.trimStart().startsWith("Session note:"))return null;let t={},n=null,r=[],s=()=>{if(n&&r.length>0){let o=r.join(`
`).trim();o&&(t[n]=o)}r=[]};for(let o of e.split(`
`).slice(1)){let i=W.find(([,c])=>o.startsWith(`${c}: `)||o===`${c}:`);i?(s(),n=i[0],r.push(o.slice(i[1].length+1).trim())):n&&r.push(o)}return s(),Object.keys(t).length>0?t:null}function Ne(e){return(e.tags??[]).includes("session_note")||(e.memory??"").trimStart().startsWith("Session note:")}function q(e){let t=null,n=Number.NEGATIVE_INFINITY;for(let r of Object.values(e))for(let s of r??[]){if(!Ne(s))continue;let o=s.created_at?new Date(s.created_at).getTime():Number.NEGATIVE_INFINITY,i=Number.isNaN(o)?Number.NEGATIVE_INFINITY:o;(t===null||i>n)&&(t=s,n=i)}return t}function J(e,t){let n=[`## Previously${t?` (${t})`:""}`,""];e.next_steps&&n.push(`**Next steps:** ${e.next_steps}`);for(let[r,s]of W){if(r==="next_steps")continue;let o=e[r];o&&n.push(`**${s}:** ${o}`)}return n.length>2?n.join(`
`):""}function V(e,t=new Date){if(!e)return"?";let n=new Date(e);if(Number.isNaN(n.getTime()))return"?";let r=(t.getTime()-n.getTime())/1e3;if(r<0&&(r=0),r<60)return"now";let s=r/60;if(s<60)return`${Math.floor(s)}m`;let o=s/60;if(o<24)return`${Math.floor(o)}h`;let i=o/24;return i<7?`${Math.floor(i)}d`:i<30?`${Math.floor(i/7)}w`:i<365?`${Math.floor(i/30)}mo`:`${Math.floor(i/365)}y`}function X(e){let t=[];for(let n of e)!n.lines||n.lines.length===0||t.push(`## Identity Card (${n.label})

${n.lines.join(`
`)}`);return t.join(`

`)}var Se=[{id:"semantic",label:"Semantic",categories:[{id:"preference",label:"Preferences",description:"User preferences: language, editor, code style, communication style",scope:"global",vaultFolder:"Semantic/Preferences"},{id:"personal_fact",label:"Personal Facts",description:"Personal details: name, timezone, role, team",scope:"global",vaultFolder:"Semantic/Personal-Facts"},{id:"technical_skill",label:"Technical Skills",description:"Known technologies, proficiency levels",scope:"global",vaultFolder:"Semantic/Technical-Skills"},{id:"domain_knowledge",label:"Domain Knowledge",description:"Industry/domain-specific knowledge",scope:"global",vaultFolder:"Semantic/Domain-Knowledge"}]},{id:"project",label:"Project",categories:[{id:"tech_stack",label:"Tech Stack",description:"Project technology choices",scope:"project",vaultFolder:"Project/Tech-Stack"},{id:"convention",label:"Conventions",description:"Coding conventions, naming, file structure",scope:"project",vaultFolder:"Project/Conventions"},{id:"architecture",label:"Architecture",description:"Design decisions, module boundaries, API patterns",scope:"project",vaultFolder:"Project/Architecture"},{id:"dependency",label:"Dependencies",description:"Packages, versions, compatibility notes",scope:"project",vaultFolder:"Project/Dependencies"}]},{id:"episodic",label:"Episodic",categories:[{id:"decision",label:"Decisions",description:"Decisions made with rationale",scope:"flexible",vaultFolder:"Episodic/Decisions"},{id:"interaction",label:"Interactions",description:"Notable past interactions/events",scope:"flexible",vaultFolder:"Episodic/Interactions"}]},{id:"procedural",label:"Procedural",categories:[{id:"workflow",label:"Workflows",description:"Git flow, CI/CD, deployment, review process",scope:"flexible",vaultFolder:"Procedural/Workflows"},{id:"procedure",label:"Procedures",description:"Step-by-step how-to patterns",scope:"flexible",vaultFolder:"Procedural/Procedures"}]},{id:"working",label:"Working",categories:[{id:"task_context",label:"Recent Context",description:"Current task, recent changes, blockers",scope:"flexible",vaultFolder:"Working/Task-Context"}]}],z=Se.flatMap(e=>e.categories),Q=z.map(e=>e.id),Z=Object.fromEntries(z.map(e=>[e.id,e.label]));var ee=8e3,ke=200;function ve(){return m("CONTEXT_MODE","index").toLowerCase()==="full"?"full":"index"}function Ie(){let e=parseInt(m("INDEX_BUDGET_TOKENS",""),10);return Number.isFinite(e)&&e>0?e:1500}function $e(){let e=m("CODE_GRAPH","auto").toLowerCase();return e==="on"||e==="off"?e:"auto"}function ne(e){if(!e||e.length===0)return"";let t=["# \u2696\uFE0F Neuralscape AUTHORITATIVE Standards (binding)","","These are organization standards set by a Neuralscape dictator. They are BINDING directives, not preferences. On any conflict they OVERRIDE personal preferences and project conventions. Follow them unless the user explicitly overrides them in this session.",""];for(let n of e)t.push(`- ${n.memory}`);return t.join(`
`)}function Ae(e){let t=[],n=0;for(let r of Q){let s=e[r];if(!s||s.length===0)continue;let i=[`## ${Z[r]||r}`];for(let c of s){let p=`- ${c.memory}`;if(n+p.length>ee)break;i.push(p),n+=p.length}if(i.length>1&&t.push(i.join(`
`)),n>=ee)break}return t.length===0?"":`# Neuralscape Memory Context

${t.join(`

`)}`}function Pe(e){let{context:t,cards:n,codeGraphAvailable:r,budgetTokens:s}=e,o=e.now??new Date,i=t.categories||{},c=[],p=ne(t.standards);p&&c.push(p);let f=X(n);f&&c.push(f);let g=q(i),a=null;if(g){let u=K(g.memory);if(u){let d=J(u,`last session, ${V(g.created_at??null,o)} ago`);d&&(c.push(d),a=g.id)}}let l=[];for(let u of Object.keys(i))for(let d of i[u]??[])d.id!==a&&l.push(d);if(l.length>0){let u=Y(l.map(G),{budgetTokens:s,now:o});c.push([`## Memory Index \u2014 ${H(u)}`,"","`#id | time | type | title | ~tokens`","",u.text].join(`
`)),c.push(v(r))}else(f||a)&&c.push(v(r));return c.length===0?"":`# Neuralscape Memory

${c.join(`

---

`)}`}async function te(e,t){try{let n=await x("/v1/extensions/dreaming/card",{pool:e,user_id:t});return n&&n.status==="ok"&&Array.isArray(n.lines)&&n.lines.length>0?n.lines:null}catch{return null}}async function Re(e){let t=$e();if(t==="on")return!0;if(t==="off")return!1;try{return await x("/v1/code-graph/query",{question:"__ns_session_start_probe__",depth:"1",token_budget:"100",user_id:e}),!0}catch{return!1}}async function Ce(){let e;try{e=await C()}catch(t){t instanceof y&&(b(t.message),process.exit(2)),b("session-start stdin read failed",t),E();return}try{if(!D()){b("missing user_id \u2014 run `/plugin config neuralscape@neuralscape-plugins` to set USER_ID (or set NEURALSCAPE_USER_ID env var as legacy fallback); skipping context injection"),E();return}let t=O(),n=M(e.cwd),r=n?x(`/v1/context/${n}`,{user_id:t,limit:String(ke)}):x("/v1/context/global",{user_id:t}),s=[];n&&s.push(te(`shared--project--${n}`,t).then(a=>a?{label:`project: ${n}`,lines:a}:null)),s.push(te(`user--${t}`,t).then(a=>a?{label:"user",lines:a}:null));let o=ve(),i=o==="index"?Re(t):Promise.resolve(!1),c;try{c=await r}catch{S("[neuralscape] memory service unreachable \u2014 continuing without memory context.");return}let p="";try{let a=await F(e.session_id);if(a.length>0){let l=a.reduce((d,N)=>d+N.lineCount,0),u=a.map(d=>`\`${d.path}\``).join(", ");p=`

# Neuralscape \u2014 Pending Observations

${a.length} buffer file(s) from prior sessions hold ${l} unprocessed tool observations: ${u}.

**Before responding to the user's first prompt**, run the \`compile-observations\` skill on each of these paths to extract significant memories using the v2 memory model. Skip noise (routine reads/edits/searches). After memories submit successfully, truncate each buffer file. Then continue with the user's request.`}}catch(a){b("listPendingBuffers failed (non-critical)",a)}let f;if(o==="full"){let a=ne(c.standards),l=Ae(c.categories||{});f=a?l?`${a}

---

${l}`:a:l}else{let l=(await Promise.all(s.map(d=>d.catch(()=>null)))).filter(d=>d!==null),u=await i.catch(()=>!1);f=Pe({context:c,cards:l,codeGraphAvailable:u,budgetTokens:Ie()})}let g=(f||"")+p;g.trim()?S(g):E()}catch(t){b("session-start hook failed",t),E()}}process.env.NEURALSCAPE_TEST!=="1"&&Ce();export{Pe as buildIndexContext,Ae as formatMemories,ne as formatStandards,$e as getCodeGraphMode,ve as getContextMode,Ie as getIndexBudgetTokens};
