"""The code-graph report fact extractor (GRAPH_REPORT.md → insights).

Graphify's GRAPH_REPORT.md is the LLM-authored narrative over a code graph:
architecture overview, module purposes, god nodes, surprising connections,
knowledge gaps. This extractor distils it into *stable* knowledge-about-the-code
memories (module purposes, boundaries, invariants, hotspots, rationale) — never
raw structure (which churns per commit and is served live by the code-graph
query tools).

Implements the :class:`ingest.extractors.FactExtractor` protocol
(``build_messages`` + ``parse``); the shared Gemini client, retries, and junk
filter live in ``MemoryService.extract_facts_only``.
"""

from __future__ import annotations

import json
import logging
import re

from schemas import MEMORY_CATEGORIES

logger = logging.getLogger(__name__)


REPORT_EXTRACTION_PROMPT = """You are a software-architecture knowledge engine. The text below is from a GRAPH_REPORT.md generated by a code-graph analysis tool over a codebase. Extract the STABLE knowledge about the codebase — the layer that stays true across commits — not raw structure.

Extract distinct insights. For EACH insight, produce an object with:
- "category": ONE of these code-graph categories:
  - "module"    — a module/community and its purpose ("the ingest package owns chunking + parsing")
  - "boundary"  — a coupling/boundary observation, esp. surprising cross-module connections
  - "invariant" — a rule the code maintains ("writes are async, reads are sync", "every memory carries a source_ref")
  - "rationale" — a documented WHY (design rationale, NOTE/HACK comments, trade-offs)
  - "hotspot"   — a god node / core abstraction many things depend on, or a churn/complexity risk
- "statement": one clear standalone sentence stating the insight
- "evidence": the report line/phrase it came from (short, verbatim), or null
- "node_refs": code-graph node/community labels it concerns (list of strings), or null
- "confidence_tag": "EXTRACTED" if the report states it directly, "INFERRED" if the report derived it, "AMBIGUOUS" if the report flags it as uncertain

Rules:
1. Prefer the report's exact wording for names and numbers. Never invent modules or dependencies not in the text.
2. Each insight must stand alone (no "as above").
3. Skip raw listings (plain file lists, import tables) — they are structure, not knowledge.
4. Skip generated boilerplate and tool banners.

Respond with a JSON object:
{
  "insights": [
    {"category":"...","statement":"...","evidence":"..."|null,"node_refs":["..."]|null,"confidence_tag":"EXTRACTED"|"INFERRED"|"AMBIGUOUS"}
  ]
}

If no insights can be extracted, return {"insights": []}.

TEXT:
"""

# Off-vocab category fallback for this adapter (architecture is the closest
# core category to "knowledge about code structure").
_FALLBACK_CATEGORY = "architecture"

_CODE_GRAPH_CATEGORIES = {"module", "boundary", "invariant", "rationale", "hotspot"}


def _clean_json(text: str) -> str:
    """Strip a Markdown code fence if the model wrapped its JSON."""
    t = text.strip()
    if t.startswith("```"):
        t = re.sub(r"^```(?:json)?\s*", "", t)
        t = re.sub(r"\s*```$", "", t)
    return t


def _render_insight(insight: dict) -> str:
    """Flatten one extracted insight into a single memory body."""
    parts: list[str] = []
    statement = (insight.get("statement") or "").strip()
    parts.append(statement)

    refs = insight.get("node_refs")
    if isinstance(refs, list):
        refs = [str(r).strip() for r in refs if str(r).strip()]
        if refs:
            parts.append(f"Concerns: {', '.join(refs[:8])}")

    evidence = (insight.get("evidence") or "").strip()
    if evidence:
        parts.append(f'Report: "{evidence}"')
    return "\n".join(p for p in parts if p)


class CodeGraphReportExtractor:
    """FactExtractor that emits stable architecture insights from GRAPH_REPORT.md."""

    name = "code_graph_report"

    def build_messages(self, text: str) -> list[dict]:
        return [{"role": "user", "content": REPORT_EXTRACTION_PROMPT + text}]

    def parse(self, response_text: str) -> list[tuple[str, str]]:
        try:
            data = json.loads(_clean_json(response_text))
            insights = data.get("insights", [])
        except (json.JSONDecodeError, AttributeError):
            logger.warning("Code-graph report extraction: response was not valid JSON — 0 insights")
            return []

        out: list[tuple[str, str]] = []
        for insight in insights:
            if not isinstance(insight, dict):
                continue
            category = str(insight.get("category", "")).strip().lower()
            # A code-graph category must have been registered into
            # MEMORY_CATEGORIES by the adapter's profile import; anything
            # off-vocab degrades so store_raw's membership check never fails.
            if category not in _CODE_GRAPH_CATEGORIES or category not in MEMORY_CATEGORIES:
                logger.debug(
                    "Code-graph report extraction: unknown category %r → %s",
                    category, _FALLBACK_CATEGORY,
                )
                category = _FALLBACK_CATEGORY
            # AMBIGUOUS report insights are dropped here (the deterministic
            # graph.json path applies the configurable floor; for LLM-read
            # report text the tag means "the report itself is unsure" — the
            # weakest signal we have, so it never becomes a memory).
            if str(insight.get("confidence_tag", "")).strip().upper() == "AMBIGUOUS":
                continue
            body = _render_insight(insight)
            if body.strip():
                out.append((category, body))
        return out
